spring:
  # H2 Setting Info
  h2:
    console:
      enabled: true  # H2 Console
      path: /h2-console  # H2 Console Path
  datasource:
    url: jdbc:h2:mem:datajpa # H2(In-Memory)
#    url: jdbc:h2:~/datajpa   # H2(Embedded)
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#        show_sql: true
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 10
#        one-indexed-parameters: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace